### ISSUE TITLE
Is it possible to do something similar in iOS?

### ISSUE THREAD

**Issue by lazercorn** [VictorGil/phoneVerifier#1]
I realize that Apple have more limitations so was wondering if it is possible to do something like this in iOS, if you know that is. Cool project btw. Will be helpful on the android side of things for sure. thanks.

**Comment by VictorGil** [comment]
Thanks for you comment, I have zero experience with iOS to be honest, but I think that it should be possible to so something similar in iOS. 
Basically, you just need a way (API) to send an SMS message (which includes the verification code) on behalf of the user (after she/he has granted the permission to your app, of course), and then a way (API) to read that message once is received on the same phone (the user should have granted also permissions to your app to read the SMS messages). All of that should be doable in iOS, but using different APIs.

**Comment by lazercorn** [comment]
Doesn't seem to be possible due to limitation on being able to read SMS messages.

https://stackoverflow.com/questions/21300138/how-can-we-read-incoming-sms-by-using-application-in-ios

Unfortunate.

**Comment by VictorGil** [comment]
Wow! iOS is more limited indeed.
